"use strict";
(() => {
  const HF_IMPORT='https://cdn.jsdelivr.net/npm/@huggingface/transformers@4.2.0';
  const MODELS=['Xenova/bge-small-en-v1.5','Xenova/all-MiniLM-L6-v2'];
  const AI_WAIT_MS=15000;
  const INTENTS=[
    {id:'recovery',title:'Recovery / very easy day',text:'recovery tired sore hard workout yesterday rest easy walk low intensity exhausted fatigue'},
    {id:'easy',title:'Easy aerobic session',text:'easy run comfortable aerobic base conversational pace simple workout today'},
    {id:'long',title:'Long endurance session',text:'long run long walk endurance distance marathon build weekly long day stamina'},
    {id:'runwalk',title:'Run / walk progression',text:'beginner run walk couch to running intervals build slowly start running'},
    {id:'speed',title:'Faster controlled intervals',text:'speed faster pace intervals tempo improve pace quick workout race speed'},
    {id:'strength',title:'Bodyweight strength',text:'strength bodyweight squats pushups core legs cross training workout no run'},
    {id:'walk',title:'Walking day',text:'walk walking low impact steps family walk active recovery easy'},
    {id:'consistency',title:'Consistency / restart',text:'missed workouts restart fell off plan consistency motivation get back on track busy'}
  ];
  let embedder=null,vectors=null,loading=null,activeModel=null,requestId=0;
  const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const timeout=(p,ms,msg)=>Promise.race([p,new Promise((_,r)=>setTimeout(()=>r(new Error(msg)),ms))]);
  function installUI(){if(document.querySelector('#strideAiCoach'))return;const screen=document.querySelector('#screen-plans'),anchor=screen?.querySelector('.planSafety');if(!screen||!anchor)return;const p=document.createElement('div');p.id='strideAiCoach';p.className='panel strideAiCoach';p.innerHTML=`<div class="strideAiHead"><div><span>HUGGING FACE • LOCAL HISTORY</span><h3>Ask Stride AI Coach</h3></div><b id="strideAiHistory">0 activities</b></div><p class="hint">Ask what training makes sense today. You get an immediate history-aware answer, then local AI improves the intent match when ready.</p><div class="strideAiInput"><textarea id="strideAiQuestion" rows="3" maxlength="320" placeholder="Examples: What should I do today? • I ran yesterday and feel tired • Help me build my long run"></textarea><button id="strideAiAsk" class="btn primary" type="button">✨ Coach me</button></div><div id="strideAiStatus" class="hint">Ready.</div><div id="strideAiAnswer" class="strideAiAnswer hidden"></div>`;anchor.insertAdjacentElement('afterend',p);document.querySelector('#strideAiAsk')?.addEventListener('click',runCoach);refreshCount();}
  function history(){const rows=(typeof activities!=='undefined'&&Array.isArray(activities))?activities:[];return[...rows].filter(a=>a&&a.date).sort((a,b)=>new Date(b.date)-new Date(a.date));}
  function refreshCount(){const e=document.querySelector('#strideAiHistory'),n=history().length;if(e)e.textContent=`${n} activit${n===1?'y':'ies'}`;}
  const daysAgo=d=>(Date.now()-new Date(d).getTime())/86400000;
  const miles=rows=>rows.reduce((s,a)=>s+(Number(a.distanceMiles)||0),0);
  const fmtMiles=n=>`${Math.max(0,n).toFixed(n<10?1:0)} mi`;
  function fmtPace(sec){if(!Number.isFinite(sec)||sec<=0)return'—';const m=Math.floor(sec/60),s=Math.round(sec%60);return`${m}:${String(s).padStart(2,'0')}/mi`;}
  function snapshot(){const h=history(),r7=h.filter(a=>daysAgo(a.date)<=7),p7=h.filter(a=>daysAgo(a.date)>7&&daysAgo(a.date)<=14),runs=r7.filter(a=>a.type==='Run'),last=h[0]||null,longest=Math.max(0,...h.filter(a=>daysAgo(a.date)<=42).map(a=>Number(a.distanceMiles)||0)),paces=runs.map(a=>Number(a.paceSecondsPerMile)).filter(Number.isFinite);return{history:h,recent7:r7,prior7:p7,runs7:runs,last,miles7:miles(r7),milesPrior:miles(p7),longestRecent:longest,avgPace:paces.length?paces.reduce((a,b)=>a+b,0)/paces.length:null,hoursSinceLast:last?Math.max(0,(Date.now()-new Date(last.date).getTime())/3600000):Infinity};}
  function lexical(q){const terms=q.toLowerCase().split(/[^a-z0-9]+/).filter(x=>x.length>2);return INTENTS.map(intent=>{const h=`${intent.title} ${intent.text}`.toLowerCase();return{intent,score:terms.reduce((n,t)=>n+(h.includes(t)?1:0),0)/Math.max(1,terms.length)}}).sort((a,b)=>b.score-a.score)[0];}
  function startAI(status){if(embedder&&vectors)return Promise.resolve(embedder);if(loading)return loading;loading=(async()=>{status.textContent='Coach answer ready • Hugging Face AI is loading in the background…';const{pipeline,env}=await import(HF_IMPORT);if(env){env.allowLocalModels=false;env.useBrowserCache=true;if(env.backends?.onnx?.wasm)env.backends.onnx.wasm.numThreads=1;}let last;for(const model of MODELS){try{const p=await pipeline('feature-extraction',model);vectors=(await p(INTENTS.map(i=>`${i.title}. ${i.text}`),{pooling:'mean',normalize:true})).tolist();embedder=p;activeModel=model;return p;}catch(e){last=e;embedder=null;vectors=null;}}throw last||new Error('AI unavailable');})().catch(e=>{loading=null;throw e;});return loading;}
  function dot(a,b){let s=0;for(let i=0;i<Math.min(a.length,b.length);i++)s+=a[i]*b[i];return s;}
  async function semantic(q,status){const p=await startAI(status),v=(await p(q,{pooling:'mean',normalize:true})).tolist()[0];return INTENTS.map((intent,i)=>({intent,score:dot(v,vectors[i])})).sort((a,b)=>b.score-a.score)[0];}
  function recommend(intent,s){const jump=s.milesPrior>0&&s.miles7>s.milesPrior*1.35;if(s.last&&s.hoursSinceLast<18&&Number(s.last.distanceMiles||0)>=3)intent=INTENTS.find(i=>i.id==='recovery');if(jump&&['long','speed'].includes(intent.id))intent=INTENTS.find(i=>i.id==='easy');const base=s.longestRecent>0?Math.max(1.5,s.longestRecent):2,longTarget=Math.min(base+.5,base*1.10+.15);const p={recovery:{title:'Keep today deliberately easy',session:'20–40 minutes of easy walking, plus optional light mobility. No pace target.',why:'Recovery protects consistency after recent work.',filter:'walk'},easy:{title:'Build the aerobic base',session:`25–40 minutes easy and conversational. Recent run pace is ${fmtPace(s.avgPace)}, but today does not need to match it.`,why:'Easy volume helps without turning every day into a test.',filter:'run'},long:{title:'Long-session progression',session:`If you feel normal, keep the next long session around ${fmtMiles(longTarget)} rather than making a huge jump. Use run/walk as needed.`,why:`Your longest saved activity in the last 6 weeks is ${fmtMiles(s.longestRecent)}.`,filter:'run'},runwalk:{title:'Use run/walk on purpose',session:'25–35 minutes alternating comfortable running and walking. Finish feeling like you could do a little more.',why:'Run/walk builds time on feet while keeping the session controllable.',filter:'run'},speed:{title:'Controlled faster work',session:'Warm up easy, then 4–6 short controlled faster efforts with easy recovery; cool down easy.',why:'A small dose of quality is enough. Skip it when recovery says otherwise.',filter:'run'},strength:{title:'Bodyweight support day',session:'Choose one built-in bodyweight session and keep every rep clean and controlled.',why:'Strength supports the running plan without another hard mileage day.',filter:'workout'},walk:{title:'Make walking count',session:'30–45 minutes at a purposeful but comfortable pace.',why:'Walking adds aerobic work with less impact.',filter:'walk'},consistency:{title:'Restart smaller than your motivation wants',session:'Pick the easiest built-in session you can complete cleanly today, then schedule the next one before you finish.',why:'Rebuild the streak instead of repaying missed workouts in one day.',filter:'all'}};return{intent,...(p[intent.id]||p.easy),sharpJump:jump};}
  function render(match,s,mode){const r=recommend(match.intent,s),last=s.last?`${s.last.type} ${fmtMiles(Number(s.last.distanceMiles)||0)} • ${Math.round(s.hoursSinceLast)}h ago`:'No saved activity yet',trend=s.milesPrior>0?`${Math.round((s.miles7/s.milesPrior-1)*100)}% vs prior 7 days`:'not enough prior-week data';return`<div class="strideAiRec"><div class="strideAiRecTop"><span>${esc(r.intent.title)}</span><b>${esc(mode)}</b></div><h3>${esc(r.title)}</h3><p><strong>Session:</strong> ${esc(r.session)}</p><p><strong>Why:</strong> ${esc(r.why)}</p><div class="strideAiFacts"><span>Last: ${esc(last)}</span><span>7-day volume: ${esc(fmtMiles(s.miles7))}</span><span>Trend: ${esc(trend)}</span><span>Runs this week: ${s.runs7.length}</span></div>${r.sharpJump?'<div class="strideAiCaution">Your saved 7-day volume is more than 35% above the previous 7 days, so the coach automatically backs away from a hard/long recommendation.</div>':''}<button class="btn secondary" id="strideAiShowPlan" type="button">Show matching built-in plans</button><small>General training guidance only. Stop or modify exercise for pain, dizziness, chest pain, or unusual shortness of breath.</small></div>`;}
  function bindPlan(match,s){document.querySelector('#strideAiShowPlan')?.addEventListener('click',()=>{const r=recommend(match.intent,s),target=[...document.querySelectorAll('.planFilter')].find(b=>b.dataset.filter===r.filter)||document.querySelector('.planFilter[data-filter="all"]');target?.click();document.querySelector('#trainingList')?.scrollIntoView({behavior:'smooth',block:'start'});});}
  async function runCoach(){const q=String(document.querySelector('#strideAiQuestion')?.value||'').trim(),status=document.querySelector('#strideAiStatus'),answer=document.querySelector('#strideAiAnswer');if(q.length<3){status.textContent='Ask what you want to do today or what you are trying to improve.';return;}const s=snapshot(),id=++requestId,initial=lexical(q);answer.innerHTML=render(initial,s,'Instant history-aware match');answer.classList.remove('hidden');bindPlan(initial,s);refreshCount();status.textContent='Coach answer ready • Hugging Face AI is improving the intent match…';try{const match=await timeout(semantic(q,status),AI_WAIT_MS,'AI startup timed out');if(id!==requestId)return;answer.innerHTML=render(match,s,'Hugging Face semantic intent');bindPlan(match,s);status.textContent=`AI ready • ${activeModel} • grounded in ${s.history.length} saved activities`;}catch(e){if(id!==requestId)return;console.warn('Stride AI unavailable',e);status.textContent='History-aware coach is active. Hugging Face AI did not finish in time, so the instant answer stayed usable instead of hanging.';}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',installUI,{once:true});else installUI();
})();
