const MI_PER_M=0.000621371,KM_PER_M=.001;
const KEYS={a:'stridefw.activities.v1',r:'stridefw.routes.v1',s:'stridefw.settings.v1'};
let map,planMap,userMarker,accuracyCircle,trackLine,planLine,shownLayer,watchId=null,lastPosition=null,gpsReady=false;
let activityType='Run',recording=false,paused=false,startedAt=null,pauseAt=null,pausedMs=0,timerId=null,trackPoints=[],planPoints=[],planMarkers=[],wakeLock=null,lastAnnounced=0,historyFilter='all';
let activities=loadArray(KEYS.a),routes=loadArray(KEYS.r),settings=loadSettings();
function loadArray(k){try{const v=JSON.parse(localStorage.getItem(k)||'[]');return Array.isArray(v)?v:[]}catch{return[]}}
function loadSettings(){try{return{units:'mi',voice:true,wake:true,follow:true,theme:'light',...JSON.parse(localStorage.getItem(KEYS.s)||'{}')}}catch{return{units:'mi',voice:true,wake:true,follow:true,theme:'light'}}}
function migrate(){if(!activities.length){const old=loadArray('runfw.activities.v2');if(old.length)activities=old}if(!routes.length){const old=loadArray('runfw.routes.v2');if(old.length)routes=old}persist()}
function persist(){localStorage.setItem(KEYS.a,JSON.stringify(activities));localStorage.setItem(KEYS.r,JSON.stringify(routes))}
function saveSettings(){settings.voice=voiceToggle.checked;settings.wake=wakeToggle.checked;settings.follow=followToggle.checked;localStorage.setItem(KEYS.s,JSON.stringify(settings))}
function applySettings(){unitsSelect.value=settings.units;voiceToggle.checked=settings.voice;wakeToggle.checked=settings.wake;followToggle.checked=settings.follow;document.body.classList.toggle('dark',settings.theme==='dark');unitLabels()}
function toggleTheme(){settings.theme=settings.theme==='dark'?'light':'dark';localStorage.setItem(KEYS.s,JSON.stringify(settings));document.body.classList.toggle('dark',settings.theme==='dark')}
function changeUnits(v){settings.units=v==='km'?'km':'mi';localStorage.setItem(KEYS.s,JSON.stringify(settings));unitLabels();updateTrack();renderPlan();renderHistory();renderStats()}
function unitLabels(){distanceLabel.textContent=settings.units==='km'?'Kilometers':'Miles';paceLabel.textContent=settings.units==='km'?'Pace / km':'Pace / mi'}
function initMaps(){map=L.map('map',{zoomControl:false}).setView([32.7555,-97.3308],13);planMap=L.map('planMap',{zoomControl:false}).setView([32.7555,-97.3308],13);const u='https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',o={maxZoom:19,attribution:'&copy; OpenStreetMap'};L.tileLayer(u,o).addTo(map);L.tileLayer(u,o).addTo(planMap);planMap.on('click',e=>{planPoints.push([e.latlng.lat,e.latlng.lng]);renderPlan()})}
function showScreen(n){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.navBtn').forEach(x=>x.classList.remove('active'));document.getElementById('screen-'+n).classList.add('active');document.getElementById('nav-'+n).classList.add('active');if(n==='plan')setTimeout(()=>planMap.invalidateSize(),50);if(n==='track')setTimeout(()=>map.invalidateSize(),50);if(n==='history')renderHistory();if(n==='stats')renderStats()}
function setActivityType(t){if(recording)return;activityType=t;document.querySelectorAll('.typeBtn').forEach(b=>b.classList.toggle('active',b.dataset.type===t))}
function enableGPS(){if(!navigator.geolocation){toast('GPS is not supported here');return}gpsBtn.disabled=true;mapStatus.textContent='Requesting precise location…';if(watchId!==null){gpsReady=true;startBtn.disabled=false;return}watchId=navigator.geolocation.watchPosition(handlePosition,handleGpsError,{enableHighAccuracy:true,maximumAge:1000,timeout:15000})}
function handlePosition(pos){const p={lat:pos.coords.latitude,lng:pos.coords.longitude,accuracy:Number.isFinite(pos.coords.accuracy)?pos.coords.accuracy:null,timestamp:pos.timestamp||Date.now()};lastPosition=p;gpsReady=true;gpsBtn.textContent='✓ GPS ready';gpsBtn.disabled=true;startBtn.disabled=recording;gpsBadge.textContent=p.accuracy?`±${Math.round(p.accuracy)} m`:'GPS on';const ll=[p.lat,p.lng];if(!userMarker)userMarker=L.circleMarker(ll,{radius:8,color:'#fff',weight:3,fillColor:'#2563eb',fillOpacity:1}).addTo(map);else userMarker.setLatLng(ll);if(!accuracyCircle)accuracyCircle=L.circle(ll,{radius:p.accuracy||10,color:'#2563eb',weight:1,opacity:.3,fillColor:'#2563eb',fillOpacity:.08}).addTo(map);else accuracyCircle.setLatLng(ll).setRadius(p.accuracy||10);if(settings.follow)map.setView(ll,Math.max(map.getZoom(),16),{animate:true});mapStatus.textContent=recording?(paused?'Paused':'Recording live'):'GPS ready — press START';if(recording&&!paused&&shouldRecord(p)){trackPoints.push(p);drawTrack();updateTrack();announceIfNeeded()}}
function handleGpsError(e){gpsReady=false;gpsBtn.disabled=false;gpsBtn.textContent='📍 Turn on GPS';startBtn.disabled=true;mapStatus.textContent='GPS unavailable — check permission';toast(e.message||'GPS error')}
function shouldRecord(p){if(p.accuracy&&p.accuracy>70)return false;if(!trackPoints.length)return true;const q=trackPoints[trackPoints.length-1],m=map.distance([q.lat,q.lng],[p.lat,p.lng]),s=Math.max(1,(p.timestamp-q.timestamp)/1000);return m>=2&&m/s<=18}
async function startActivity(){if(!gpsReady||!lastPosition){enableGPS();return}recording=true;paused=false;startedAt=Date.now();pauseAt=null;pausedMs=0;lastAnnounced=0;trackPoints=[{...lastPosition,timestamp:Date.now()}];clearShown();drawTrack();updateTrack();startWrap.classList.add('hidden');recordControls.classList.remove('hidden');document.querySelectorAll('.typeBtn').forEach(b=>b.disabled=true);goalInput.disabled=true;mapStatus.textContent='Recording live';timerId=setInterval(updateTrack,1000);if(settings.wake)await requestWakeLock()}
function togglePause(){if(!recording)return;paused=!paused;if(paused){pauseAt=Date.now();pauseBtn.textContent='▶ Resume';mapStatus.textContent='Paused'}else{if(pauseAt)pausedMs+=Date.now()-pauseAt;pauseAt=null;pauseBtn.textContent='Ⅱ Pause';mapStatus.textContent='Recording live'}updateTrack()}
function finishActivity(){if(!recording)return;if(paused&&pauseAt){pausedMs+=Date.now()-pauseAt;pauseAt=null}const sec=Math.round(elapsedMs()/1000),miles=trackMeters()*MI_PER_M,name=prompt('Name this activity',`${activityType} — ${new Date().toLocaleDateString()}`)||`${activityType} — ${new Date().toLocaleDateString()}`;activities.unshift({id:Date.now(),name,type:activityType,date:new Date().toISOString(),distanceMiles:round(miles,3),elapsedSeconds:sec,paceSecondsPerMile:miles>.02?Math.round(sec/miles):null,coords:trackPoints.map(p=>[round(p.lat,6),round(p.lng,6)])});persist();recording=false;paused=false;clearInterval(timerId);timerId=null;releaseWakeLock();startWrap.classList.remove('hidden');startBtn.disabled=!gpsReady;recordControls.classList.add('hidden');pauseBtn.textContent='Ⅱ Pause';document.querySelectorAll('.typeBtn').forEach(b=>b.disabled=false);goalInput.disabled=false;mapStatus.textContent='Saved — nice work';toast('Activity saved');renderHistory();renderStats()}
function elapsedMs(){if(!startedAt)return 0;const cp=paused&&pauseAt?Date.now()-pauseAt:0;return Math.max(0,Date.now()-startedAt-pausedMs-cp)}
function trackMeters(){return pathMeters(trackPoints.map(p=>[p.lat,p.lng]),map)}
function drawTrack(){if(trackLine)trackLine.remove();if(trackPoints.length)trackLine=L.polyline(trackPoints.map(p=>[p.lat,p.lng]),{color:'#ff5a1f',weight:6,opacity:.95,lineJoin:'round'}).addTo(map)}
function updateTrack(){const meters=trackMeters(),sec=Math.round(elapsedMs()/1000),dist=displayMeters(meters);distanceMetric.textContent=dist.toFixed(2);timeMetric.textContent=formatDuration(sec);paceMetric.textContent=meters>25?formatPace(settings.units==='km'?sec/(meters*KM_PER_M):sec/(meters*MI_PER_M)):'--:--';const goal=Number(goalInput.value||0);if(goal>0&&dist>=goal&&recording)mapStatus.textContent='Goal reached — great job!'}
function announceIfNeeded(){if(!settings.voice||!('speechSynthesis'in window))return;const d=displayMeters(trackMeters()),whole=Math.floor(d);if(whole>lastAnnounced&&whole>0){lastAnnounced=whole;const u=settings.units==='km'?'kilometer':'mile';speechSynthesis.speak(new SpeechSynthesisUtterance(`${whole} ${u}${whole===1?'':'s'}. Pace ${paceMetric.textContent}.`))}}
async function requestWakeLock(){try{if('wakeLock'in navigator)wakeLock=await navigator.wakeLock.request('screen')}catch{}}
function releaseWakeLock(){try{wakeLock&&wakeLock.release()}catch{}wakeLock=null}
function centerOnMe(){if(lastPosition)map.setView([lastPosition.lat,lastPosition.lng],17,{animate:true});else enableGPS()}
function fitActive(){const l=trackLine||shownLayer;if(l)map.fitBounds(l.getBounds(),{padding:[24,24]});else centerOnMe()}
function clearShown(){if(shownLayer){shownLayer.remove();shownLayer=null}}
function planCenterOnMe(){if(lastPosition)planMap.setView([lastPosition.lat,lastPosition.lng],16,{animate:true});else enableGPS()}
function addMyLocationToPlan(){if(!lastPosition){enableGPS();toast('Turn on GPS first');return}planPoints.push([lastPosition.lat,lastPosition.lng]);renderPlan()}
function undoPlan(){planPoints.pop();renderPlan()}
function reversePlan(){planPoints.reverse();renderPlan()}
function closePlan(){if(planPoints.length<3)return;if(planMap.distance(planPoints[0],planPoints[planPoints.length-1])>3)planPoints.push([...planPoints[0]]);renderPlan()}
function clearPlan(){planPoints=[];routeName.value='';renderPlan()}
function renderPlan(){if(planLine)planLine.remove();planMarkers.forEach(m=>m.remove());planMarkers=[];if(planPoints.length){planLine=L.polyline(planPoints,{color:'#16a34a',weight:6,opacity:.95,lineJoin:'round'}).addTo(planMap);planPoints.forEach((p,i)=>planMarkers.push(L.circleMarker(p,{radius:i===0?7:5,color:'#fff',weight:2,fillColor:i===0?'#16a34a':'#111827',fillOpacity:1}).addTo(planMap)))}const meters=pathMeters(planPoints,planMap);planDistance.textContent=`${displayMeters(meters).toFixed(2)} ${settings.units}`;planPointsCount.textContent=planPoints.length;planBadge.textContent=`${planPoints.length} point${planPoints.length===1?'':'s'}`}
function savePlan(){if(planPoints.length<2){toast('Add at least two points');return}const miles=pathMeters(planPoints,planMap)*MI_PER_M,name=routeName.value.trim()||`Route — ${displayMiles(miles).toFixed(1)} ${settings.units}`;routes.unshift({id:Date.now(),name,date:new Date().toISOString(),distanceMiles:round(miles,3),coords:planPoints.map(p=>[round(p[0],6),round(p[1],6)])});persist();routeName.value='';toast('Route saved');renderHistory()}
function fitPlan(){if(planLine)planMap.fitBounds(planLine.getBounds(),{padding:[24,24]});else planCenterOnMe()}
function setHistoryFilter(f,b){historyFilter=f;document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderHistory()}
function renderHistory(){historyList.innerHTML='';const rows=[];activities.forEach((a,i)=>{if(historyFilter==='all'||historyFilter===a.type)rows.push({kind:'activity',index:i,date:new Date(a.date),data:a})});routes.forEach((r,i)=>{if(historyFilter==='all'||historyFilter==='Route')rows.push({kind:'route',index:i,date:new Date(r.date),data:r})});rows.sort((a,b)=>b.date-a.date);if(!rows.length){historyList.innerHTML='<div class="panel hint">Nothing here yet. Track an activity or save a route.</div>';return}rows.forEach(row=>{const el=document.createElement('div');el.className='historyItem';if(row.kind==='activity'){const a=row.data,d=displayMiles(Number(a.distanceMiles||0)),p=a.paceSecondsPerMile?convertPace(a.paceSecondsPerMile):null;el.innerHTML=`<div class="historyTop"><div><div class="historyTitle">${esc(a.name)}</div><div class="historyMeta">${esc(a.type||'Activity')} • ${new Date(a.date).toLocaleString()}</div></div></div><div class="miniMetrics"><div class="mini"><b>${d.toFixed(2)}</b><span>${settings.units}</span></div><div class="mini"><b>${formatDuration(a.elapsedSeconds||0)}</b><span>Time</span></div><div class="mini"><b>${p?formatPace(p):'--:--'}</b><span>Pace</span></div></div><div class="smallActions"><button class="btn secondary" onclick="showActivity(${row.index})">Show map</button><button class="btn danger" onclick="deleteActivity(${row.index})">Delete</button></div>`}else{const r=row.data,d=displayMiles(Number(r.distanceMiles||0));el.innerHTML=`<div class="historyTop"><div><div class="historyTitle">${esc(r.name)}</div><div class="historyMeta">Saved route • ${new Date(r.date).toLocaleDateString()}</div></div></div><div class="miniMetrics"><div class="mini"><b>${d.toFixed(2)}</b><span>${settings.units}</span></div><div class="mini"><b>${(r.coords||[]).length}</b><span>Points</span></div><div class="mini"><b>Route</b><span>Type</span></div></div><div class="smallActions"><button class="btn secondary" onclick="loadRoute(${row.index})">Edit / use</button><button class="btn danger" onclick="deleteRoute(${row.index})">Delete</button></div>`}historyList.appendChild(el)})}
function showActivity(i){const a=activities[i];if(!a||!a.coords?.length)return;showScreen('track');clearShown();shownLayer=L.polyline(a.coords,{color:'#7c3aed',weight:6,opacity:.9}).addTo(map);map.fitBounds(shownLayer.getBounds(),{padding:[24,24]});mapStatus.textContent=a.name}
function loadRoute(i){const r=routes[i];if(!r)return;planPoints=(r.coords||[]).map(p=>[p[0],p[1]]);routeName.value=r.name;showScreen('plan');renderPlan();setTimeout(fitPlan,70)}
function deleteActivity(i){if(confirm('Delete this activity?')){activities.splice(i,1);persist();renderHistory();renderStats()}}
function deleteRoute(i){if(confirm('Delete this route?')){routes.splice(i,1);persist();renderHistory()}}
function renderStats(){const now=Date.now(),day=86400000,sum=d=>activities.filter(a=>now-new Date(a.date).getTime()<=d*day).reduce((s,a)=>s+Number(a.distanceMiles||0),0),total=activities.reduce((s,a)=>s+Number(a.distanceMiles||0),0),longest=activities.reduce((m,a)=>Math.max(m,Number(a.distanceMiles||0)),0),runs=activities.filter(a=>a.type==='Run'&&a.paceSecondsPerMile),avg=runs.length?runs.reduce((s,a)=>s+Number(a.paceSecondsPerMile||0),0)/runs.length:null;stat7.textContent=displayMiles(sum(7)).toFixed(1)+' '+settings.units;stat30.textContent=displayMiles(sum(30)).toFixed(1)+' '+settings.units;statTotal.textContent=displayMiles(total).toFixed(1)+' '+settings.units;statCount.textContent=activities.length;statLongest.textContent=displayMiles(longest).toFixed(1)+' '+settings.units;statPace.textContent=avg?formatPace(convertPace(avg)):'--:--'}
function exportData(){const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),activities,routes,settings},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`stride-fw-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)}
function clearAllData(){if(confirm('Delete every saved activity and route?')){activities=[];routes=[];persist();renderHistory();renderStats();toast('Data cleared')}}
function pathMeters(points,m){let t=0;for(let i=1;i<points.length;i++)t+=m.distance(points[i-1],points[i]);return t}
function displayMeters(m){return settings.units==='km'?m*KM_PER_M:m*MI_PER_M}function displayMiles(m){return settings.units==='km'?m*1.609344:m}function convertPace(s){return settings.units==='km'?s/1.609344:s}
function formatDuration(s){s=Math.max(0,Math.round(Number(s)||0));const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),x=s%60;return h?`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`}
function formatPace(s){s=Math.max(0,Math.round(Number(s)||0));return`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}function round(v,p){const f=10**p;return Math.round(v*f)/f}function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(m){toastBox.textContent=m;toastBox.classList.add('show');clearTimeout(toastBox._t);toastBox._t=setTimeout(()=>toastBox.classList.remove('show'),1800)}
window.addEventListener('load',()=>{migrate();applySettings();initMaps();renderPlan();renderHistory();renderStats();updateTrack()});